name: visualize
on:
  push:
    branches:
    - main
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          commit_message: default
          artifact_name: diagram
