name: visualize
on:
  push:
    branches:
    - main
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Repo visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          commit_message: default
          artifact_name: diagram
